Algoritmo "Solicitar Recursos Trabalho"

Var
N: caractere
I, TT: inteiro
Inicio

escreva ("Digite seu nome: ")
leia (N)
escreva ("Digite sua idade: ")
leia (I)
escreva ("Digite seu tempo de trabalho: ")
leia (TT)

se (I >=65) e (TT >= 30) entao 
escreva ("Apta para a solicitação de recursos previdenciarios!")
senao
escreva ("Não apta para a solicitação de recursos previdenciarios!")
fimse
fimalgoritmo