Algoritmo "Solicitar Recursos"

Var
N, G: caractere
I: inteiro
Inicio

escreva ("Digite seu nome: ")
leia (N)
escreva ("Digite sua idade: ")
leia (I)
escreva ("Digite seu genero, F para feminino e M para masculino: ")
leia (G)

se (I >=60) e (G= "F") entao 
escreva ("Apta para a solicitação de recursos previdenciarios!")
senao
escreva ("Não apta para a solicitação de recursos previdenciarios!")
fimse
fimalgoritmo

